### ISSUE TITLE
Help Submitting a PR for a Complicated Tesseract `autogen.sh` Patch?  

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/formula-patches#124]
While diagnosing Homebrew/homebrew-core#10380, I incidentally noticed and filed tesseract-ocr/tesseract#750 upstream in the process (the issue was tangential, but I thought I'd go ahead and fix it in the process; I'll likely have to file a separate PR for whatever patch finally solves the Homebrew Core issue I referenced if upstream doesn't push a new release.)  I've been trying to figure out how to extract the versions of the sequence of commits from that PR which upstream backported from its `master` branch to its `3.05` branch, which is where we'd want to get a patch from since 3.05 is the version of Tesseract currently offered by Homebrew, into a single patch file to host here, but I haven't yet been able to figure out how I might go about doing that.  [What little advice I've found regarding bundling multiple commits into a single patch](http://stackoverflow.com/questions/616556/how-do-you-squash-commits-into-one-patch-with-git-format-patch) doesn't explain how to do it from a branch other than `master`, let _alone_ how to do it for commits that have since become buried by some more commit history.  Otherwise, I'd just go straight to submitting a PR for use in another new one in Homebrew Core.

**Comment by RandomDSdevel** [comment]
In particular, I need to create an aggregate patch for the following upstream Tesseract commits:  

* [Commit `efb89f8`](https://github.com/tesseract-ocr/tesseract/commit/efb89f8133c0526693efc2cf42ae79ef4397dcae):  

  [`autogen.sh`:]  Abstract the absolute path of `libtoolize` or `glibtoolize` away into `$LIBTOOLIZE`.  

  Increase portability by insulating `autogen.sh` from platform variance.  
* [Commit `ed49959`](https://github.com/tesseract-ocr/tesseract/commit/ed49959d2a599e0ef7faf9087a9c16bf292c751d):  

  [`autogen.sh`:]  Reduce in-script comment block width to 80 characters.  

  This is with respect to the comment preceding the `libtoolize`/`glibtoolize` existence check I introduced.  
* [Commit `3671de0`](https://github.com/tesseract-ocr/tesseract/commit/3671de002dcea069f2229341439c04400b11d400):  

  [`autogen.sh`:]  Clarify `libtoolize`/`glibtoolize` existence check error message.

  Explicitly mention the latter variant of the tool inside said error message.  
* [Commit `d9a9876`](https://github.com/tesseract-ocr/tesseract/commit/d9a9876a7024955ee91ded14dce24c86e2e75e14):  

  [`autogen.sh`:]  Improve `libtoolize` invocation message.  

  Use the `$LIBTOOLIZE` variable inside the message to abstract over the two possible variants of the tool which can be invoked.

**Comment by RandomDSdevel** [comment]
Since the patch that would result from resolving this issue would only make a cosmetic change to the build process, which isn't failing without these changes, should I perhaps just go ahead and close this issue and let propagating those changes through to Homebrew Core be deferred until Tesseract's next full official release?

**Comment by ilovezfs** [comment]
@RandomDSdevel that should be fine.

**Comment by RandomDSdevel** [comment]
Thanks, @ilovezfs.
