### ISSUE TITLE
Remove unused patches

### ISSUE THREAD

**Issue by issyl0** [Homebrew/formula-patches#906]
Some of the patches here might be unused in core formulae. We should 🚮 the unused ones.

Each patch is referred to by its commit SHA in here so it'll stick around even if removed and our search went wrong somehow and it is still in use.

This could be a GitHub Action, "oi, remove these patches" in this repo or an audit.

```shell
issyl0 at pictor in /opt/homebrew/Library/Taps/homebrew/homebrew-core on master
❯ git grep "Homebrew/formula-patches" | uniq | wc -l
     365
```

**Comment by issyl0** [comment]
Oh, nice, #905 beat me to it!

**Comment by SMillerDev** [comment]
Yeah, detection could use some work there if you have some suggestions
